file=open("geetha.txt","w")
file.write("this is geetha")
file.close()
file=open("geetha.txt","r")
print(file.read())
file.close()
file=open("geetha.txt","a")
file.write("  i love u annayya")
file.close()
file=open("geetha.txt","r")
print(file.read())
file.close()
